### ISSUE TITLE
埋まっているカプセルを掘り起こす

### ISSUE THREAD

**Issue by NNN-kakimoto** [uyupun/cyme-capsule-backend#23]
Endpoint
POST /api/capsule/dig
Controller CapsuleController
method dig

1. リクエストに含まれているカプセルIDと同じIDのカプセルを検索する
2. そのカプセルがまだ誰にも掘り起こされていないかチェック(後でもいい
3. カプセルの `dug_user_id` をリクエストしたユーザーのIDに更新
4. 最終的なカプセル情報をJSON化→レスポンスする

**Comment by HiEN63** [comment]
PR した
